version: "3.4"

services:
  sji3.api:
    image: ${DOCKER_REGISTRY-}sji3api
    build:
      context: .
      dockerfile: SJI3.API/Dockerfile

  sji3.identity:
    image: ${DOCKER_REGISTRY-}sji3identity
    build:
      context: .
      dockerfile: SJI3.Identity/Dockerfile

  #sji3.worker:
  #  image: ${DOCKER_REGISTRY-}sji3worker
  #  build:
  #    context: .
  #    dockerfile: SJI3.Worker/Dockerfile



