version: "3.4"

services:
  sonarqube:
    image: sonarqube:community
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
    restart: unless-stopped

  sji3.api:
    image: ${DOCKER_REGISTRY-}sji3api
    build:
      context: .
      dockerfile: SJI3.API/Dockerfile

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
